### PR TITLE
[Feature] GitHub friends full implementation

### PR DESCRIPTION
**Pull request by Bukii**
**This PR includes:** ✨ 
- [x] a separate section for friends (doesn't show up, when the user is not authenticated)
- [x] purple circle color for friends to fit github
- [x] hasMore button specifically for friends (fetchStories and fetchFriendsStories work independently)

Thanks @bar9 for helping! :)

### CODE REVIEW

**Review by TheFern2 — COMMENTED** [review]
@Bukii A few minor details:

- The text that says Github Friends on the Sidebar has a little bit less space, than Explore to the line.
- When you have friends, and you click on a circle friend, you can see the add/remove button flash from add to remove. It should stay as remove the entire time. For example if the heart is liked, the heart doesn't flash from empty to filled.

**Comment by Bukii** [comment]
@TheFern2 I will fix the text alignment, but the add/remove bug you mentioned is because there's an api call that checks if the auth user is still following this person.
I can put the call at the very top, so it gets called before anything else. What do you think?

**Comment by TheFern2** [comment]
Yeah we can try that, and see if it works better visually.

**Comment by Bukii** [comment]
> @Bukii A few minor details:
> 
> * The text that says Github Friends on the Sidebar has a little bit less space, than Explore to the line.
> * When you have friends, and you click on a circle friend, you can see the add/remove button flash from add to remove. It should stay as remove the entire time. For example if the heart is liked, the heart doesn't flash from empty to filled.

Regarding the text alignment. May you explain it to me please (maybe add an image).

**Comment by TheFern2** [comment]
The gap between the text and upper portion looks like is different, or am I going blind lol. Github Friends looks a bit closer.

image

**Comment by Bukii** [comment]
Oh, I see. No problem, I will fix that :)

**Pull request merged**
