### PR TITLE
Fixed issue_template 

### PR DESCRIPTION
**Pull request by Suryadevelops**
image

I fixed issue_templates but i aslo found this or template is not working properly i will make a fix soon

### CODE REVIEW

**Comment by Suryadevelops** [comment]
Fixed PR template

**Comment by TheFern2** [comment]
Please restore funding yml file.

**Comment by Suryadevelops** [comment]
@TheFern2 

Restores funding.yml

**Comment by TheFern2** [comment]
@Suryadevelops Thanks for your contributions, unfortunately only feature requests shows for some reason. This is going to create confusion as bug report is not showing. Will close, and use your initial templates for the mean time.

**Comment by Suryadevelops** [comment]
@TheFern2

I understand the problem in merging this 🙂

**Pull request closed without merging**
