### PR TITLE
Update .gitignore

### PR DESCRIPTION
**Pull request by Ishaan28malik**
Adding yarn.lock and package.json to `gitignore`

### CODE REVIEW

**Comment by benawad** [comment]
why

**Comment by Ishaan28malik** [comment]
@benawad because every time is build is made and the dev is not updating the yarn modules, then there is always a difference in the versions of the modules and hence to avoid those conflicts of the versions, it is recommended to put them in `.gitignore`

**Comment by bar9** [comment]
probably related to https://github.com/ide-stories/vscode-stories/pull/84#issuecomment-729941321
I'll keep an eye out for this.
@Ishaan28malik do you know of a guide or best practice about how to handle this? I will only put up 'best practice' rules once something becomes a repeated pain, or if everybody overwhelmingly agrees on something

**Comment by Ishaan28malik** [comment]
@bar9 Sure , But can you please clarify if you want me to share the best practise around management of `yarn.lock` and `package.json` files or in general better practices ?

**Comment by TheFern2** [comment]
I think this PR is invalid, we shouldn't exclude any lock or package.json files. The only time the lock file will change is when the json file changes, no?

@Bukii have you had any issues with lock or json files this week while we have been going back and forth with PR reviews? I haven't. Now if someone is making package json changes without npm install and not checking in those changes that's an issue for sure but that can be caught when reviewing the PR, if you do npm install and the lock file is changed, PR submitter needs to fix the lock file first.

**Comment by Bukii** [comment]
> I think this PR is invalid, we shouldn't exclude any lock or package.json files. The only time the lock file will change is when the json file changes and you do `npm i`, no?
> 
> @Bukii have you had any issues with lock or json files this week while we have been going back and forth with PR reviews? I haven't. Now if someone is making package json changes without npm install and not checking in those changes that's an issue for sure but that can be caught when reviewing the PR, if you do npm install and the lock file is changed, PR submitter needs to fix the lock file first.

No, I didn't have any issues. If I am understanding this PR right and it's about the difference between package-lock and yarn.lock, there's something called yarn import, which basically uses package-lock in order to keep yarn and package-lock in sync.

**Comment by TheFern2** [comment]
I dunno what is the best practice here, usually in most of my solo projects I checkin lock files. I've found both ways yes merge lock files, and no don't use them at all. In my opinion it is a bit hard to enforce a user to use npm or yarn, I particularly use npm (pnpm). And I've tried to use yarn before, but is hard to break the habit of npm commands.

Yarn import will generate a yarn-lock based on package-lock, but if new packages are installed, I don't think it will update package-lock. In other words yarn import is made for yarn users, where the repo is only updated with npm. There is no yarn export to update the package-lock file.

https://gajus.medium.com/stop-using-package-lock-json-or-yarn-lock-909035e94328
https://classic.yarnpkg.com/blog/2018/06/04/yarn-import-package-lock/

From a technical point of view, what are the consequences if we remove both lock files? I don't think we should remove package.json file though.

**Comment by TheFern2** [comment]
Closing. This will be taken care of, once we decide which package manager is used whether is yarn or npm as per #106 . The lock file should always be checked in, I really don't think there will be an instance of the lock file not being updated, unless for some odd reason someone adds a package to package.json without installing. And without testing the code change, but this will be definitely caught during code review. 

If the code reviewer does a git pull, and npm/yarn install the lock file should remain the same.

**Pull request closed without merging**
