### PR TITLE
[Feature] add and remove friend icon

### PR DESCRIPTION
**Pull request by Bukii**
This is the frontend to the add and remove friend backend PR.

### CODE REVIEW

**Comment by bar9** [comment]
@Bukii thanks for the contribution, this seems to be a useful addition without complicating things. I'll merge this. Can you change the PR to be without the package.json.lock?

**Comment by Bukii** [comment]
> @Bukii thanks for the contribution, this seems to be a useful addition without complicating things. I'll merge this. Can you change the PR to be without the package-lock.json

Sure :)

**Comment by bar9** [comment]
I meant reverting the change, not deleting the file. So the PR only contains the relevant changes an I can test it

**Comment by Bukii** [comment]
Oh, sry. Is it ok, if I take the package-lock from master?

**Comment by bar9** [comment]
Frontend looking good, thanks @Bukii. Reviewing backend

**Pull request merged**
